spring:
  datasource:
    driver className: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/neoforum
    username: root
    password: root
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:forum
    #username: sa
    #password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: insertuser
    password: insertpassword
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
flyway.locations.filesystem: db/migration
jwt:
  secret: secret