apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neoforum-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neoforum-app
                port:
                  number: 8080